"""Extend models

Revision ID: 5e66d11cb201
Revises: 1a31ce608336
Create Date: 2025-11-13 22:32:46.709505

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e66d11cb201'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aimodel',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aimodel_created_at'), 'aimodel', ['created_at'], unique=False)
    op.create_index(op.f('ix_aimodel_name'), 'aimodel', ['name'], unique=False)
    op.create_index(op.f('ix_aimodel_provider'), 'aimodel', ['provider'], unique=False)
    op.create_index(op.f('ix_aimodel_updated_at'), 'aimodel', ['updated_at'], unique=False)
    op.create_index(op.f('ix_aimodel_version'), 'aimodel', ['version'], unique=False)
    op.create_table('organization',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('plan_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_created_at'), 'organization', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_index(op.f('ix_organization_plan_type'), 'organization', ['plan_type'], unique=False)
    op.create_index(op.f('ix_organization_slug'), 'organization', ['slug'], unique=True)
    op.create_index(op.f('ix_organization_updated_at'), 'organization', ['updated_at'], unique=False)
    op.create_table('tag',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_created_at'), 'tag', ['created_at'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_index(op.f('ix_tag_updated_at'), 'tag', ['updated_at'], unique=False)
    op.create_table('apikey',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_created_at'), 'apikey', ['created_at'], unique=False)
    op.create_index(op.f('ix_apikey_key_hash'), 'apikey', ['key_hash'], unique=True)
    op.create_index(op.f('ix_apikey_updated_at'), 'apikey', ['updated_at'], unique=False)
    op.create_index(op.f('ix_apikey_user_id'), 'apikey', ['user_id'], unique=False)
    op.create_table('organizationmembership',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'member', 'viewer', name='membershiprole'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_organizationmembership_created_at'), 'organizationmembership', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizationmembership_organization_id'), 'organizationmembership', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organizationmembership_role'), 'organizationmembership', ['role'], unique=False)
    op.create_index(op.f('ix_organizationmembership_updated_at'), 'organizationmembership', ['updated_at'], unique=False)
    op.create_index(op.f('ix_organizationmembership_user_id'), 'organizationmembership', ['user_id'], unique=False)
    op.create_table('setting',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Enum('global_', 'user', 'organization', name='settingscope'), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_created_at'), 'setting', ['created_at'], unique=False)
    op.create_index(op.f('ix_setting_key'), 'setting', ['key'], unique=False)
    op.create_index(op.f('ix_setting_organization_id'), 'setting', ['organization_id'], unique=False)
    op.create_index(op.f('ix_setting_scope'), 'setting', ['scope'], unique=False)
    op.create_index(op.f('ix_setting_updated_at'), 'setting', ['updated_at'], unique=False)
    op.create_index(op.f('ix_setting_user_id'), 'setting', ['user_id'], unique=False)
    op.create_table('content',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_created_at'), 'content', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_item_id'), 'content', ['item_id'], unique=False)
    op.create_index(op.f('ix_content_role'), 'content', ['role'], unique=False)
    op.create_index(op.f('ix_content_updated_at'), 'content', ['updated_at'], unique=False)
    op.create_table('event',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['aimodel.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_actor_id'), 'event', ['actor_id'], unique=False)
    op.create_index(op.f('ix_event_created_at'), 'event', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_item_id'), 'event', ['item_id'], unique=False)
    op.create_index(op.f('ix_event_organization_id'), 'event', ['organization_id'], unique=False)
    op.create_index(op.f('ix_event_updated_at'), 'event', ['updated_at'], unique=False)
    op.create_table('fileasset',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_fileasset_created_at'), 'fileasset', ['created_at'], unique=False)
    op.create_index(op.f('ix_fileasset_item_id'), 'fileasset', ['item_id'], unique=False)
    op.create_index(op.f('ix_fileasset_owner_id'), 'fileasset', ['owner_id'], unique=False)
    op.create_index(op.f('ix_fileasset_updated_at'), 'fileasset', ['updated_at'], unique=False)
    op.create_table('itemtaglink',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('embedding',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=True),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['aimodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_content_id'), 'embedding', ['content_id'], unique=True)
    op.create_index(op.f('ix_embedding_created_at'), 'embedding', ['created_at'], unique=False)
    op.create_index(op.f('ix_embedding_item_id'), 'embedding', ['item_id'], unique=False)
    op.create_index(op.f('ix_embedding_updated_at'), 'embedding', ['updated_at'], unique=False)
    op.add_column('item', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('item', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('item', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_item_created_at'), 'item', ['created_at'], unique=False)
    op.create_index(op.f('ix_item_organization_id'), 'item', ['organization_id'], unique=False)
    op.create_index(op.f('ix_item_owner_id'), 'item', ['owner_id'], unique=False)
    op.create_index(op.f('ix_item_title'), 'item', ['title'], unique=False)
    op.create_index(op.f('ix_item_type'), 'item', ['type'], unique=False)
    op.create_index(op.f('ix_item_updated_at'), 'item', ['updated_at'], unique=False)
    op.create_foreign_key(None, 'item', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('user', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_user_auth_provider'), 'user', ['auth_provider'], unique=False)
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_is_superuser'), 'user', ['is_superuser'], unique=False)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_is_superuser'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_user_auth_provider'), table_name='user')
    op.drop_column('user', 'extras')
    op.drop_column('user', 'auth_provider')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_index(op.f('ix_item_updated_at'), table_name='item')
    op.drop_index(op.f('ix_item_type'), table_name='item')
    op.drop_index(op.f('ix_item_title'), table_name='item')
    op.drop_index(op.f('ix_item_owner_id'), table_name='item')
    op.drop_index(op.f('ix_item_organization_id'), table_name='item')
    op.drop_index(op.f('ix_item_created_at'), table_name='item')
    op.drop_column('item', 'organization_id')
    op.drop_column('item', 'meta_data')
    op.drop_column('item', 'type')
    op.drop_column('item', 'updated_at')
    op.drop_column('item', 'created_at')
    op.drop_index(op.f('ix_embedding_updated_at'), table_name='embedding')
    op.drop_index(op.f('ix_embedding_item_id'), table_name='embedding')
    op.drop_index(op.f('ix_embedding_created_at'), table_name='embedding')
    op.drop_index(op.f('ix_embedding_content_id'), table_name='embedding')
    op.drop_table('embedding')
    op.drop_table('itemtaglink')
    op.drop_index(op.f('ix_fileasset_updated_at'), table_name='fileasset')
    op.drop_index(op.f('ix_fileasset_owner_id'), table_name='fileasset')
    op.drop_index(op.f('ix_fileasset_item_id'), table_name='fileasset')
    op.drop_index(op.f('ix_fileasset_created_at'), table_name='fileasset')
    op.drop_table('fileasset')
    op.drop_index(op.f('ix_event_updated_at'), table_name='event')
    op.drop_index(op.f('ix_event_organization_id'), table_name='event')
    op.drop_index(op.f('ix_event_item_id'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_created_at'), table_name='event')
    op.drop_index(op.f('ix_event_actor_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_content_updated_at'), table_name='content')
    op.drop_index(op.f('ix_content_role'), table_name='content')
    op.drop_index(op.f('ix_content_item_id'), table_name='content')
    op.drop_index(op.f('ix_content_created_at'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_setting_user_id'), table_name='setting')
    op.drop_index(op.f('ix_setting_updated_at'), table_name='setting')
    op.drop_index(op.f('ix_setting_scope'), table_name='setting')
    op.drop_index(op.f('ix_setting_organization_id'), table_name='setting')
    op.drop_index(op.f('ix_setting_key'), table_name='setting')
    op.drop_index(op.f('ix_setting_created_at'), table_name='setting')
    op.drop_table('setting')
    op.drop_index(op.f('ix_organizationmembership_user_id'), table_name='organizationmembership')
    op.drop_index(op.f('ix_organizationmembership_updated_at'), table_name='organizationmembership')
    op.drop_index(op.f('ix_organizationmembership_role'), table_name='organizationmembership')
    op.drop_index(op.f('ix_organizationmembership_organization_id'), table_name='organizationmembership')
    op.drop_index(op.f('ix_organizationmembership_created_at'), table_name='organizationmembership')
    op.drop_table('organizationmembership')
    op.drop_index(op.f('ix_apikey_user_id'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_updated_at'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_key_hash'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_created_at'), table_name='apikey')
    op.drop_table('apikey')
    op.drop_index(op.f('ix_tag_updated_at'), table_name='tag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_created_at'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_organization_updated_at'), table_name='organization')
    op.drop_index(op.f('ix_organization_slug'), table_name='organization')
    op.drop_index(op.f('ix_organization_plan_type'), table_name='organization')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_created_at'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_aimodel_version'), table_name='aimodel')
    op.drop_index(op.f('ix_aimodel_updated_at'), table_name='aimodel')
    op.drop_index(op.f('ix_aimodel_provider'), table_name='aimodel')
    op.drop_index(op.f('ix_aimodel_name'), table_name='aimodel')
    op.drop_index(op.f('ix_aimodel_created_at'), table_name='aimodel')
    op.drop_table('aimodel')
    # ### end Alembic commands ###
